#!/bin/bash
# Script to help configure Vercel environment variables
# Usage: Follow the interactive steps below

echo "=========================================="
echo "Vercel Firebase Configuration Script"
echo "=========================================="
echo ""
echo "IMPORTANT: You must do this in Vercel Dashboard"
echo "Cannot be automated - requires manual setup"
echo ""
echo "Follow these steps exactly:"
echo ""
echo "1. Go to: https://vercel.com/walmi11/nsnwpyup/settings/environment-variables"
echo ""
echo "2. Click 'Add New Environment Variable'"
echo ""
echo "3. Add EACH variable below (repeat step 2 for each):"
echo ""
echo "Variable 1:"
echo "  Name: NEXT_PUBLIC_FIREBASE_API_KEY"
echo "  Value: AIzaSyCzdq81WVpuczl28Rv6EMuZK8bpXHuhj-Q"
echo ""
echo "Variable 2:"
echo "  Name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
echo "  Value: mon-app-cours.firebaseapp.com"
echo ""
echo "Variable 3:"
echo "  Name: NEXT_PUBLIC_FIREBASE_PROJECT_ID"
echo "  Value: mon-app-cours"
echo ""
echo "Variable 4:"
echo "  Name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
echo "  Value: mon-app-cours.firebasestorage.app"
echo ""
echo "Variable 5:"
echo "  Name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
echo "  Value: 246473751652"
echo ""
echo "Variable 6:"
echo "  Name: NEXT_PUBLIC_FIREBASE_APP_ID"
echo "  Value: 1:246473751652:web:a7b8b465fd6ade31313371"
echo ""
echo "=========================================="
echo "After adding all 6 variables:"
echo "=========================================="
echo ""
echo "4. Go to: https://vercel.com/walmi11/nsnwpyup/deployments"
echo ""
echo "5. Find the latest failed deployment"
echo ""
echo "6. Click 'Redeploy' button"
echo ""
echo "7. Wait 2-3 minutes for build to complete"
echo ""
echo "8. Once status is green ✓, visit:"
echo "   https://nsnwpyup.vercel.app"
echo ""
echo "=========================================="
echo "Verification:"
echo "=========================================="
echo ""
echo "✓ If you see the app loading = SUCCESS"
echo "✓ If you can sign up with email = SUCCESS"
echo "✓ If app says 'Select a subject' = SUCCESS"
echo ""
echo "❌ If still 404 = Check all 6 variables were added correctly"
echo "❌ If build fails = Check Vercel build logs for errors"
echo ""
